### ISSUE TITLE
可以提升的点

### ISSUE THREAD

**Issue by Ainult** [sysuyyds/NoMoreUSC#2]
1. 门卫扫开以后的画面：侧边那个反馈按钮里面的流水号建议随机生成，或者固定为一个比较真实的流水号，而不是111111
2. 生成二维码以后的界面：最下面缺少以下图标
![image](https://user-images.githubusercontent.com/34310975/197337913-e0b95034-e1f5-474b-9688-c535bb81add1.png)

**Comment by sysuyyds** [comment]
可以考虑开个pull request?
